using BobTheDiceMaster.GameOfSchool;

namespace BobTheDiceMaster
{
  /// <summary>
  /// A game of school for a single player with decisions as input parameters
  /// and dice values generated by an <see cref="IDie"/> passed to the constructor.
  /// </summary>
  public class GameOfSchoolWithDice : GameOfSchoolWithDiceBase
  {
    public GameOfSchoolWithDice(IDie dice) : base(dice)
    {
      // do nothing
    }

    /// <summary>
    /// Score a combination <paramref name="combination"/>.
    /// Only possible in <see cref="GameOfSchoolState.Rolled"/> game state.
    /// </summary>
    public void ScoreCombination(CombinationTypes combination)
    {
      ScoreCombinationProtected(combination);
    }

    /// <summary>
    /// Cross out a combination <paramref name="combination"/>.
    /// Only possible in <see cref="GameOfSchoolState.Rolled"/> game state.
    /// </summary>
    public void CrossOutCombination(CombinationTypes combination)
    {
      CrossOutCombinationProtected(combination);
    }

    /// <summary>
    /// Generate new values for dice at indexes <paramref name="diceIndexes" />.
    /// Only possible in the <see cref="GameOfSchoolState.Rolled"/> game state.
    /// </summary>
    public void RerollDiceAtIndexes(int[] diceIndexes)
    {
      ApplyRerollToDiceAtIndexesProtected(dice.Roll(diceIndexes.Length), diceIndexes);
    }
  }
}
